table dim_year
	lineageTag: 8db97382-4b5c-4dd1-b1d8-1ecbda822696

	column year
		dataType: int64
		formatString: 0
		lineageTag: 72a55cef-2857-4128-827c-bda67ee136c9
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column decade
		dataType: int64
		formatString: 0
		lineageTag: 72001858-99a8-4644-b4c9-a26087b46da5
		summarizeBy: none
		sourceColumn: decade

		annotation SummarizationSetBy = Automatic

	column period_label
		dataType: string
		lineageTag: 2fd804cc-aa8e-4b5b-b92d-b71b26eb60ff
		summarizeBy: none
		sourceColumn: period_label

		annotation SummarizationSetBy = Automatic

	partition dim_year = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("access_mode=read_only;dsn=mental_health_duckdb", [HierarchicalNavigation=true]),
				    mental_health_Database = Source{[Name="mental_health",Kind="Database"]}[Data],
				    main_Schema = mental_health_Database{[Name="main",Kind="Schema"]}[Data],
				    dim_year_Table = main_Schema{[Name="dim_year",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_year_Table,{"date"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

